# Header
menu:
  Home: /
  Archives: /archives
  中文: javascript:void(0)
# rss: /atom.xml
# github: https://github.com/becker-posner-blog
# banner: "images/banner.jpg"
subtitle: 'A Blog by Gary Becker and Richard Posner'

# Content
excerpt_link: Comments
fancybox: true
recent_posts_limits: 10

# Sidebar
sidebar: right
widgets:
- links
- calendar
- recent_posts
- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
baidu_tongji:
favicon: /favicon.ico

twitter:
fb_admins:
fb_app_id:

# Toc
toc:
  article: false   ## show contents in article.
  aside: false     ## show contents in aside.
# Scroll to top
go_top: true

# baidu share
baidushare: false

# blogroll
links:
- name: Gary Becker
  link: https://www.chicagobooth.edu/faculty/nobel-laureates/gary-becker
- name: Richard Posner
  link: https://www.law.uchicago.edu/faculty/posner-r

# about me
about_me:
  title: Home Pages
  gravatar: a@abc.com
  avatar: /images/github.jpg
  texts:
  - Hi,I'm howiefh.

# display updated
display_updated: false

# 不蒜子
busuanzi: true

# calendar
calendar:
  language: en

# valine comment system. https://valine.js.org
valine:
  enable: false # if you want use valine,please set this value is true
  appId:  # leancloud application app id
  appKey:  # leancloud application app key
  notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: false # valine verify code (true/false)
  pageSize: 10 # comment list page size
  avatar: mm # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info
